plugins {
    id 'com.android.application'
}

android {
    namespace 'uy.com.traslados.conductor'
    compileSdk 35

    defaultConfig {
        applicationId 'uy.com.traslados.conductor'
        minSdk 26
        targetSdk 35
        versionCode 122
        versionName '11.4-R10.4'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
